In [5]:
import numpy as np

arr1 = np.arange(15).reshape(3,5) # 1차원 배열이:3, 2차원 배열이 5개
# arr1
# arr1.shape
# arr1.dtype

dtype('int64')

In [6]:



arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Four arithmetic operations are possible between arrays.
arr3 = np.array([
    [1,2,3],
    [4,5,6]
], dtype = np.float64)

arr4 = np.array([
    [1,1,1],
    [2,2,2]
], dtype = np.float64)

# print(arr3 - arr4)
print(arr3 + arr4)

[[2. 3. 4.]
 [6. 7. 8.]]
